services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    
    networks:
      - elmandado_network
  
  sync-service:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: sync-service
    ports:
      - '${SERVICE_PORT}:3000'
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: ${MONGO_HOST}
    depends_on:
      - mongodb
    networks:
      - elmandado_network

volumes:
  mongodb_data:

networks:
  elmandado_network: