services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: elmandado
    networks:
      - elmandado_network
  
  sync-service:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: sync-service
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017
      MONGO_DB: el_mandado_test
    networks:
      - elmandado_network

volumes:
  mongodb_data:

networks:
  elmandado_network: